include_guard()

set(SKL_L1_CACHE_LINE_SIZE_OPTIONS 64bytes 128bytes 512bytes)
set(SKL_REAL_TYPE_OPTIONS          Single Double)
set(SKL_LOG_LEVEL_OPTIONS          DEBUG INFO WARNING ERROR FATAL MUTE)
set(SKL_LTO_OPTIONS                NONE STANDARD THIN FULL)
set(SKL_BUILD_TYPE_OPTIONS         DEV STAGING SANITIZING SHIPPING)
